Validate assumption

diff --git a/.github/actions/temp-checkout-submodules-and-bootstrap/action.yaml b/.github/actions/temp-checkout-submodules-and-bootstrap/action.yaml
--- a/.github/actions/temp-checkout-submodules-and-bootstrap/action.yaml
+++ b/.github/actions/temp-checkout-submodules-and-bootstrap/action.yaml
@@ -40,8 +40,8 @@ runs:
       # this point onwards.
       shell: bash
       run: |
-        du -sh $HOME/.cipd-cache-dir/ || true
-        rm -rf $HOME/.cipd-cache-dir/ || echo "Removing cipd cache dir failed"
+        du -sh $HOME/asdf/ || true
+        rm -rf $HOME/asdf/ || echo "Removing cipd cache dir failed"
     - name: Dump disk info after checkout submodule & Bootstrap
       shell: bash
       run: scripts/dump_diskspace_info.sh
