Add compile-time code generation using zap for app-templates
- add support for gn builds
- add support for cmake builds
- update esp32 build logic
- update pre-generation script
- split out app and idl codegen
- update template used so zap_generate_all only generates IDLs for apps
- updated CI unit tests

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -251,6 +251,14 @@ jobs:
                        --pregen-dir ./zzz_pregenerated \
                        build \
                     "
+            - name: Check no code generation in output
+              run: |
+                  CNT=$(find -name "CHIPClusters.h" out | wc -l)
+                  if [ "${CNT}" != "0" ]; then
+                     echo "ERROR: found unexpected generated files:"
+                     find -name "CHIPClusters.h" out
+                     exit 1
+                  fi
             - name: Undo code pre-generation changes (make compile time codegen work again)
               run: |
                   rm -rf ./zzz_pregenerated
diff --git a/.github/workflows/examples-esp32.yaml b/.github/workflows/examples-esp32.yaml
--- a/.github/workflows/examples-esp32.yaml
+++ b/.github/workflows/examples-esp32.yaml
@@ -93,6 +93,14 @@ jobs:
                         build \
                         --copy-artifacts-to out/artifacts \
                      "
+            - name: Check no code generation in output
+              run: |
+                  CNT=$(find -name "CHIPClusters.h" out | wc -l)
+                  if [ "${CNT}" != "0" ]; then
+                     echo "ERROR: found unexpected generated files:"
+                     find -name "CHIPClusters.h" out
+                     exit 1
+                  fi
             - name: Undo code pregeneration changes
               run: |
                   rm -rf ./zzz_pregenerated
