Add new steps to new yaml

diff --git a/.github/workflows/coverage.yaml b/.github/workflows/coverage.yaml
--- a/.github/workflows/coverage.yaml
+++ b/.github/workflows/coverage.yaml
@@ -22,6 +22,267 @@ env:
     CHIP_NO_LOG_TIMESTAMPS: true
 
 jobs:
+    build_linux_gcc_debug:
+        name: Build on Linux (gcc_debug)
+
+        runs-on: ubuntu-latest
+        if: github.actor != 'restyled-io[bot]'
+
+        container:
+            image: ghcr.io/project-chip/chip-build:125
+            volumes:
+                - "/:/runner-root-volume"
+                - "/tmp/log_output:/tmp/test_logs"
+            options: --privileged --sysctl "net.ipv6.conf.all.disable_ipv6=0
+                net.ipv4.conf.all.forwarding=1 net.ipv6.conf.all.forwarding=1"
+
+        steps:
+            - name: Dump GitHub context
+              env:
+                  GITHUB_CONTEXT: ${{ toJSON(github) }}
+              run: echo "$GITHUB_CONTEXT"
+            - name: Dump Concurrency context
+              env:
+                  CONCURRENCY_CONTEXT: ${{ github.ref }}-${{ github.workflow }}-${{ (github.event_name == 'pull_request' && github.event.number) || (github.event_name == 'workflow_dispatch' && github.run_number) || github.sha }}
+              run: echo "$CONCURRENCY_CONTEXT"
+            - name: Checkout
+              uses: actions/checkout@v4
+            - name: Try to ensure the directories for core dumping exist and we
+                  can write them.
+              run: |
+                  mkdir /tmp/cores || true
+                  sysctl -w kernel.core_pattern=/tmp/cores/core.%u.%p.%t || true
+            - name: Checkout submodules & Bootstrap
+              uses: ./.github/actions/checkout-submodules-and-bootstrap
+              with:
+                platform: linux
+            - name: Initialize CodeQL
+              if: ${{ inputs.run-codeql  }}
+              uses: github/codeql-action/init@v3
+              with:
+                  languages: "cpp"
+            - name: Setup Build
+              run: scripts/build/gn_gen.sh --args="chip_config_memory_debug_checks=true chip_config_memory_debug_dmalloc=false"
+            - name: Run Build
+              run: scripts/run_in_build_env.sh "ninja -C ./out"
+            - name: Run Tests
+              run: scripts/tests/gn_tests.sh
+            - name: Set up Build Without Detail Logging
+              run: scripts/build/gn_gen.sh --args="chip_detail_logging=false"
+            - name: Run Build Without Detail Logging
+              run: scripts/run_in_build_env.sh "ninja -C ./out"
+            - name: Set up Build Without Progress Logging
+              run: scripts/build/gn_gen.sh --args="chip_detail_logging=false chip_progress_logging=false"
+            - name: Run Build Without Progress Logging
+              run: scripts/run_in_build_env.sh "ninja -C ./out"
+            - name: Set up Build Without Error Logging
+              run: scripts/build/gn_gen.sh --args="chip_detail_logging=false chip_progress_logging=false chip_error_logging=false"
+            - name: Run Build Without Error Logging
+              run: scripts/run_in_build_env.sh "ninja -C ./out"
+            - name: Set up Build Without Logging
+              run: scripts/build/gn_gen.sh --args="chip_logging=false"
+            - name: Run Build Without Logging
+              run: scripts/run_in_build_env.sh "ninja -C ./out"
+            - name: Uploading core files
+              uses: actions/upload-artifact@v4
+              if: ${{ failure() && !env.ACT }}
+              with:
+                  name: crash-core-linux-gcc-debug
+                  path: /tmp/cores/
+                  # Cores are big; don't hold on to them too long.
+                  retention-days: 5
+            - name: Perform CodeQL Analysis
+              if: ${{ inputs.run-codeql  }}
+              uses: ./.github/actions/perform-codeql-analysis
+              with:
+                language: cpp
+            # OBJDIR on linux is > 10K files and takes more than 50 minutes to upload, usually
+            # having the job timeout.
+            #
+            # If re-enabling, some subset of this should be picked
+            #
+            # - name: Uploading objdir for debugging
+            #   uses: actions/upload-artifact@v4
+            #   if: ${{ failure() && !env.ACT }}
+            #   with:
+            #       name: crash-objdir-linux-gcc-debug
+            #       path: out/
+            #       # objdirs are big; don't hold on to them too long.
+            #       retention-days: 5
+
+    build_linux:
+        name: Build on Linux (fake, gcc_release, clang, simulated)
+
+        runs-on: ubuntu-latest
+        if: github.actor != 'restyled-io[bot]'
+
+        container:
+            image: ghcr.io/project-chip/chip-build:125
+            volumes:
+                - "/:/runner-root-volume"
+                - "/tmp/log_output:/tmp/test_logs"
+            options: --privileged --sysctl "net.ipv6.conf.all.disable_ipv6=0
+                net.ipv4.conf.all.forwarding=1 net.ipv6.conf.all.forwarding=1"
+
+        steps:
+            - name: Dump GitHub context
+              env:
+                  GITHUB_CONTEXT: ${{ toJSON(github) }}
+              run: echo "$GITHUB_CONTEXT"
+            - name: Dump Concurrency context
+              env:
+                  CONCURRENCY_CONTEXT: ${{ github.ref }}-${{ github.workflow }}-${{ (github.event_name == 'pull_request' && github.event.number) || (github.event_name == 'workflow_dispatch' && github.run_number) || github.sha }}
+              run: echo "$CONCURRENCY_CONTEXT"
+            - name: Checkout
+              uses: actions/checkout@v4
+              with:
+                  fetch-depth: 2
+                  persist-credentials: true
+            - name: Try to ensure the directories for core dumping exist and we
+                  can write them.
+              run: |
+                  mkdir /tmp/cores || true
+                  sysctl -w kernel.core_pattern=/tmp/cores/core.%u.%p.%t || true
+            - name: Checkout submodules & Bootstrap
+              uses: ./.github/actions/checkout-submodules-and-bootstrap
+              with:
+                platform: linux
+            - name: Initialize CodeQL
+              if: ${{ inputs.run-codeql  }}
+              uses: github/codeql-action/init@v3
+              with:
+                  languages: "cpp"
+            - name: Setup and Build Simulated Device
+              run: |
+                  BUILD_TYPE=simulated
+                  GN_ARGS='chip_tests_zap_config="app1" chip_project_config_include_dirs=["../../examples/placeholder/linux/apps/app1/include", "../../config/standalone"] chip_config_network_layer_ble=false'
+                  CHIP_ROOT_PATH=examples/placeholder/linux
+                  CHIP_ROOT_PATH="$CHIP_ROOT_PATH" BUILD_TYPE="$BUILD_TYPE" scripts/build/gn_gen.sh --args="$GN_ARGS"
+                  scripts/run_in_build_env.sh "ninja -C ./out/$BUILD_TYPE"
+            - name: Setup Build, Run Build and Run Tests
+              run: |
+                  BUILD_TYPE=gcc_release scripts/build/gn_gen.sh --args="is_debug=false"
+                  scripts/run_in_build_env.sh "ninja -C ./out/gcc_release"
+                  BUILD_TYPE=gcc_release scripts/tests/gn_tests.sh
+            - name: Clean output
+              run: rm -rf ./out
+            - name: Run Tests with sanitizers
+              # Sanitizer tests are not likely to find extra issues so running the same tests
+              # as above repeatedly on every pull request seems extra time. Instead keep this run
+              # for master only
+              if: github.event.pull_request.number == null
+              env:
+                  LSAN_OPTIONS: detect_leaks=1
+              run: |
+                  for BUILD_TYPE in asan tsan ubsan; do
+                      case $BUILD_TYPE in
+                          "asan") GN_ARGS='is_clang=true is_asan=true';;
+                          "msan") GN_ARGS='is_clang=true is_msan=true';;
+                          "tsan") GN_ARGS='is_clang=true is_tsan=true chip_enable_wifi=false';;
+                          "ubsan") GN_ARGS='is_clang=true is_ubsan=true';;
+                      esac
+
+                      rm -rf ./out/sanitizers
+                      BUILD_TYPE=sanitizers scripts/build/gn_gen.sh --args="$GN_ARGS" --add-export-compile-commands=*
+                      BUILD_TYPE=sanitizers scripts/tests/gn_tests.sh
+                  done
+            - name: Generate tests with sanitizers (for tidy)
+              if: github.event.pull_request.number != null
+              run: |
+                  rm -rf ./out/sanitizers
+                  BUILD_TYPE=sanitizers scripts/build/gn_gen.sh --args="is_clang=true is_asan=true" --add-export-compile-commands=*
+            - name: Ensure codegen is done for sanitize
+              run: |
+                  ./scripts/run_in_build_env.sh "./scripts/run_codegen_targets.sh out/sanitizers"
+            - name: Find changed files
+              id: changed-files
+              uses: tj-actions/changed-files@v46
+              with:
+                # Exclude all files under "third_party/"
+                files-ignore: |
+                  third_party/
+
+            - name: Clang-tidy validation
+              # NOTE: clang-tidy crashes on CodegenDataModel_Write due to Nullable/std::optional check.
+              #       See https://github.com/llvm/llvm-project/issues/97426
+              env:
+                  ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.changed_files }}
+              run: |
+                  touch out/changed_files.txt
+                  for file in ${ALL_CHANGED_FILES}; do
+                      echo "$file changed and will be considered for tidy"
+                      echo "$file" >>out/changed_files.txt
+                  done
+
+                  ./scripts/run_in_build_env.sh \
+                    "./scripts/run-clang-tidy-on-compile-commands.py \
+                       --compile-database out/sanitizers/compile_commands.json \
+                       --file-exclude-regex '/(repo|zzz_generated|lwip/standalone)/|-ReadImpl|-InvokeSubscribeImpl|CodegenDataModel_Write|QuieterReporting' \
+                       --file-list-file out/changed_files.txt \
+                       check \
+                    "
+            - name: Clean output
+              run: rm -rf ./out
+            - name: Build using build_examples.py
+              run: |
+                  ./scripts/run_in_build_env.sh \
+                    "./scripts/build/build_examples.py \
+                       --target linux-x64-minmdns-ipv6only-clang \
+                       --target linux-x64-rpc-console \
+                       build \
+                    "
+            - name: Create a pre-generate directory and ensure compile-time codegen would fail
+              run: |
+                  ./scripts/run_in_build_env.sh "./scripts/codepregen.py ./zzz_pregenerated"
+                  mv scripts/codegen.py scripts/codegen.py.renamed
+                  mv scripts/tools/zap/generate.py scripts/tools/zap/generate.py.renamed
+            - name: Clean output
+              run: rm -rf ./out
+            - name: Build using build_examples.py (pregen)
+              run: |
+                  ./scripts/run_in_build_env.sh \
+                    "./scripts/build/build_examples.py \
+                       --target linux-x64-all-clusters-ipv6only-clang \
+                       --target linux-x64-chip-tool-ipv6only-clang \
+                       --pregen-dir ./zzz_pregenerated \
+                       build \
+                    "
+            - name: Undo code pre-generation changes (make compile time codegen work again)
+              run: |
+                  rm -rf ./zzz_pregenerated
+                  mv scripts/codegen.py.renamed scripts/codegen.py
+                  mv scripts/tools/zap/generate.py.renamed scripts/tools/zap/generate.py
+            - name: Run fake linux tests with build_examples
+              run: |
+                  ./scripts/run_in_build_env.sh \
+                    "./scripts/build/build_examples.py --target linux-fake-tests build"
+            - name: Perform CodeQL Analysis
+              if: ${{ inputs.run-codeql  }}
+              uses: ./.github/actions/perform-codeql-analysis
+              with:
+                language: cpp
+
+            - name: Uploading core files
+              uses: actions/upload-artifact@v4
+              if: ${{ failure() && !env.ACT }}
+              with:
+                  name: crash-core-linux
+                  path: /tmp/cores/
+                  # Cores are big; don't hold on to them too long.
+                  retention-days: 5
+            # OBJDIR on linux is > 10K files and takes more than 50 minutes to upload, usually
+            # having the job timeout.
+            #
+            # If re-enabling, some subset of this should be picked
+            #
+            # - name: Uploading objdir for debugging
+            #   uses: actions/upload-artifact@v4
+            #   if: ${{ failure() && !env.ACT }}
+            #   with:
+            #       name: crash-objdir-linux
+            #       path: out/
+            #       # objdirs are big; don't hold on to them too long.
+            #       retention-days: 5
     build_linux_python_lib:
         name: Build on Linux (python_lib)
 
@@ -75,5 +336,5 @@ jobs:
                 chmod +x codecov
                 ./codecov --verbose upload-process --fail-on-error -t ${{ secrets.CODECOV_TOKEN }} -n 'service'-${{ github.run_id }} -F service -f src/controller/python/test/unit_tests/coverage.xml
                 rm -rf src/controller/python/test/unit_tests/coverage.xml
-            - name: Clean previous outputs
-              run: rm -rf out pyenv
+                rm -rf src/controller/python/test/unit_tests/.coverage
+                rm -rf out pyenv
