Add ktfmt download and execution

diff --git a/.github/workflows/kotlin-style.yaml b/.github/workflows/kotlin-style.yaml
--- a/.github/workflows/kotlin-style.yaml
+++ b/.github/workflows/kotlin-style.yaml
@@ -7,6 +7,11 @@ on:
       - ".github/workflows/kotlin-style.yaml"
       - "kotlin-detect-config.yaml"
 
+concurrency:
+    group: ${{ github.ref }}-${{ github.workflow }}-${{ (github.event_name == 'pull_request' && github.event.number) || (github.event_name == 'workflow_dispatch' && github.run_number) || github.sha }}
+    cancel-in-progress: true
+
+
 jobs:
   detekt:
     name: Static code analysis
@@ -33,9 +38,27 @@ jobs:
       - uses: actions/setup-java@v2
         with:
           distribution: 'adopt'
-          java-version: '11'
+          java-version: '17'
 
-      - name: "ktfmt"
-        uses: rsookram/ktfmt-action@v1
-        with:
-          style: kotlinlang
+      - name: Download ktfmt
+        run: |
+          cd /tmp
+          wget "https://repo1.maven.org/maven2/com/facebook/ktfmt/0.44/ktfmt-0.44-jar-with-dependencies.jar" 
+
+      - name: Format kotlin files
+        run: |
+          find src examples -name '*.kt' \
+            | xargs java -jar /tmp/ktfmt-0.44-jar-with-dependencies.jar
+
+      - name: Ensure git works in current working directory
+        run: git config --global --add safe.directory `pwd`
+
+      - name: Check for uncommited changes
+        run: |
+            git add .
+            # Show the full diff
+            git diff-index -p HEAD --
+            # Also show just the files that are different, to make it easy
+            # to tell at a glance what might be going on.  And throw in
+            # --exit-code to make this job fail if there is a difference.
+            git diff-index --exit-code HEAD --
