Update lint.yml to provide error messages for ember and emAf symbols
Why: to improve the experience when running CI/CD jobs, and providing information to the developer of what parts are failing so that they can be fixed more quickly

How: by encapsulating the matches in a variable, then checking if it has value or not, and then `echo` the matches. Otherwise, exit the job regularly with code 0.

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -274,11 +274,14 @@ jobs:
                   Check for use of 'emberAf' symbols
               if: always()
               run: |
-                  git grep -I -n '\<emberAf[A-Za-z0-9_]*' -- './*' \
+                  emberAf_matches=$(git grep -I -n '\<emberAf[A-Za-z0-9_]*' -- './*' \
                     ':(exclude).github/workflows/lint.yml' \
                     ':(exclude)src/app/util/*' \
                     ':(exclude)zzz_generated/app-common/app-common/zap-generated/access/Accessors.h' \
-                    ':(exclude)src/app/zap-templates/templates/app/attributes/Accessors-src.zapt' && exit 1 || exit 0
+                    ':(exclude)src/app/zap-templates/templates/app/attributes/Accessors-src.zapt') \
+                    && echo "Error: Found 'emberAf' symbols in the following files and lines:" \
+                    && echo "$emberAf_matches" \
+                    && exit 1 || exit 0
 
             # First pattern: emberAf
             # ---
@@ -286,11 +289,14 @@ jobs:
                   Check for use of 'emAf' symbols
               if: always()
               run: |
-                  git grep -I -n '\<emAf[A-Za-z0-9_]*' -- './*' \
+                  emAf_matches=$(git grep -I -n '\<emAf[A-Za-z0-9_]*' -- './*' \
                     ':(exclude).github/workflows/lint.yml' \
                     ':(exclude)src/app/util/*' \
                     ':(exclude)zzz_generated/app-common/app-common/zap-generated/access/Accessors.h' \
-                    ':(exclude)src/app/zap-templates/templates/app/attributes/Accessors-src.zapt' && exit 1 || exit 0
+                    ':(exclude)src/app/zap-templates/templates/app/attributes/Accessors-src.zapt') \
+                    && echo "Error: Found 'emAf' symbols in the following files and lines:" \
+                    && echo "$emAf_matches" \
+                    && exit 1 || exit 0
             # Second pattern: emAf
             # git grep exits with 0 if it finds a match, but we want
             # to fail (exit nonzero) on match.  And we want to exclude this file,
