Add lint step for IDLs in workflows, ensure lint can be run with act

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -29,6 +29,7 @@ jobs:
 
         steps:
             - uses: Wandalen/wretry.action@v1.0.15
+              if: ${{ !env.ACT }}
               name: Checkout
               with:
                   action: actions/checkout@v3
@@ -36,6 +37,32 @@ jobs:
                       token: ${{ github.token }}
                   attempt_limit: 3
                   attempt_delay: 2000
+            # To use act like:
+            #   act -j full_android
+            #
+            # Note you likely still need to have non submodules setup for the
+            # local machine, like:
+            #   git submodule deinit --all
+            - uses: actions/checkout@v3
+              if: ${{ env.ACT }}
+              name: Checkout (ACT for local build)
+
+            - name: Check for matter lint errors
+              if: always()
+              run: |
+                 for idl_file in $(find . -name '*.matter'); do
+                     # TODO: all these conformance failures should be fixed
+                     if [ "$idl_file" == './examples/window-app/common/window-app.matter' ]; then continue; fi
+                     if [ "$idl_file" == './examples/log-source-app/log-source-common/log-source-app.matter']; then continue; fi
+                     if [ "$idl_file" == './examples/placeholder/linux/apps/app1/config.matter']; then continue; fi
+                     if [ "$idl_file" == './examples/placeholder/linux/apps/app2/config.matter']; then continue; fi
+                     if [ "$idl_file" == './examples/thermostat/thermostat-common/thermostat.matter']; then continue; fi
+                     if [ "$idl_file" == './examples/all-clusters-app/all-clusters-common/all-clusters-app.matter']; then continue; fi
+                     if [ "$idl_file" == './examples/lighting-app/lighting-common/lighting-app.matter']; then continue; fi
+                     if [ "$idl_file" == './examples/log-source-app/log-source-common/log-source-app.matter']; then continue; fi
+
+                     ./scripts/run_in_build_env.sh "./scripts/idl_lint.py --log-level warn $idl_file" >/dev/null || exit 1
+                 done
 
             - name: Check broken links
               # On-push disabled until the job can run fully green
