Make sure we're not using non-type-safe attribute reads. (#25029)
Gets rid of the emberAfReadServerAttribute define, and adds a lint to restrict
emberAfReadAttribute use to the implementation of the type-safe reads.

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -193,3 +193,12 @@ jobs:
               if: always()
               run: |
                   git grep -n 'NSLog(' -- src/darwin/Framework/CHIP && exit 1 || exit 0
+
+            # git grep exits with 0 if it finds a match, but we want
+            # to fail (exit nonzero) on match.  And we want to exclude this file,
+            # to avoid our grep regexp matching itself, as well as excluding the files
+            # that implement the type-safe accessors
+            - name: Check for use of 'emberAfReadAttribute' instead of the type-safe getters
+              if: always()
+              run: |
+                  git grep -n 'emberAfReadAttribute' -- './*' ':(exclude).github/workflows/lint.yml' ':(exclude)src/app/util/af.h' ':(exclude)zzz_generated/app-common/app-common/zap-generated/attributes/Accessors.cpp' ':(exclude)src/app/zap-templates/templates/app/attributes/Accessors-src.zapt' ':(exclude)src/app/util/attribute-table.cpp'  && exit 1 || exit 0
